version: '3'
services:
    consul-server-leader:
        image: consul:latest
        restart: always
        container_name: consul-server-leader
        command: "agent -server -bootstrap -ui -node=consul-server-leader -client=0.0.0.0"
        volumes:
            - ./consul/conf:/consul/config
            - ./consul/data:/consul/data
        environment:
            - CONSUL_BIND_INTERFACE=eth0
            - 'CONSUL_LOCAL_CONFIG={"connect": {"enabled": true}}'
        ports:
            - "8500:8500"
    
    nginx:
        image: nginx:stable-alpine-perl
        restart: always
        privileged: true
        container_name: nginx
        working_dir: /wwwroot
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./logs/nginx:/var/log/nginx
            - ../wwwroot:/wwwroot
            - /usr/share/nginx/html:/usr/share/nginx/html
            - /etc/localtime:/etc/localtime:ro

    mysql:
        image: mysql:5.7
        restart: always
        container_name: php-mysql-5-7
        privileged: true
        volumes:
            - ./mysql/conf:/etc/mysql
            - /var/lib/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        command:
            --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --explicit_defaults_for_timestamp=true
        ports:
            - "3306:3306"
    
    redis:
        image: redis:6.0.10
        restart: always
        container_name: redis
        privileged: true
        command: redis-server /etc/redis/redis.conf
        ports:
            - "6379:6379"
        volumes:
            - ./redis/redis.conf:/etc/redis/redis.conf
            - ./redis/data:/data

    grpc-skeleton:
        build: 
            context: ./gRPC/
            dockerfile: Dockerfile
        restart: always
        privileged: true
        container_name: grpc-skeleton
        working_dir: /wwwroot
        volumes:
            - ../wwwroot:/wwwroot
        ports:
            - "8000:8080"
            - "8001:8081"
        tty: true

    swoole:
        image: gnfy/swoole-fpm:1.1
        #build:
        #    context: ./swoole/
        #    dockerfile: Dockerfile
        restart: always
        privileged: true
        container_name: swoole-4-8-1 
        working_dir: /wwwroot
        ports:
            - "9000:9000"
            - "9501:9501"
            - "9502:9502"
        volumes:
            - ../wwwroot:/wwwroot
            - ./php/php.ini:/usr/local/etc/php/php.ini
            - ./logs/php:/usr/local/var/log
            - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
            - /usr/share/nginx/html:/usr/share/nginx/html

    zipkin:
        image: openzipkin/zipkin
        container_name: zipkin
        privileged: true
        restart: always
#        environment:
#            - STORAGE_TYPE=mysql
#            # Point the zipkin at the storage backend
#            - MYSQL_DB=zipkin
#            - MYSQL_USER=root
#            - MYSQL_PASS=root
#            - MYSQL_HOST=php-mysql-5-7
#            - MYSQL_TCP_PORT=3306
#            # Uncomment to enable scribe
#            # - SCRIBE_ENABLED=true
#            # Uncomment to enable self-tracing
#            # - SELF_TRACING_ENABLED=true
#            # Uncomment to enable debug logging
#            # - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
        ports:
            # Port used for the Zipkin UI and HTTP Api
            - "9411:9411"
