version: '3'
services:
    consul-server-leader:
        image: consul:latest
        restart: always
        container_name: consul-server-leader
        command: "agent -server -bootstrap -ui -node=consul-server-leader -client=0.0.0.0"
        environment:
            - CONSUL_BIND_INTERFACE=eth0
            - 'CONSUL_LOCAL_CONFIG={"connect": {"enabled": true}}'
        ports:
            - "8500:8500"
    nginx:
        image: nginx:latest
        restart: always
        privileged: true
        container_name: nginx-1-9
        working_dir: /wwwroot
        ports:
            - "80:80"
            - "8080:80"
            - "443:443"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./logs/nginx:/var/log/nginx
            - ./wwwroot:/wwwroot
            - /usr/share/nginx/html:/usr/share/nginx/html
            - /etc/localtime:/etc/localtime:ro
    php:
        image: gnfy/php-fpm-swoole:1.5
        restart: always
        privileged: true
        container_name: php-7-4-13
        working_dir: /wwwroot
        ports:
            - "9000:9000"
            - "9501:9501"
        volumes:
            - ./php/php.ini:/usr/local/etc/php/php.ini
            - ./logs/php:/usr/local/var/log
            - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
            - ./wwwroot:/wwwroot
            - /usr/share/nginx/html:/usr/share/nginx/html
            - /etc/localtime:/etc/localtime:ro

    mysql:
        image: mysql:5.7
        restart: always
        container_name: php-mysql-5-7
        privileged: true
        volumes:
            - ./mysql/conf:/etc/mysql
            - /var/lib/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        command:
            --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --explicit_defaults_for_timestamp=true
        ports:
            - "3306:3306"
    
    redis:
        image: redis:6.0.10
        restart: always
        container_name: redis
        privileged: true
        command: redis-server /etc/redis/redis.conf
        ports:
            - "6379:6379"
        volumes:
            - ./redis/redis.conf:/etc/redis/redis.conf
            - ./redis/data:/data
