FROM golang:1.17.3-alpine

MAINTAINER gnfy

RUN mkdir /opt/protoc && \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk update && \
    apk add --no-cache curl unzip && \
    # 下载protobuf
    curl -sfL https://github.com/protocolbuffers/protobuf/releases/download/v3.19.1/protoc-3.19.1-linux-x86_64.zip -o protoc.zip && \
    unzip -o protoc.zip -d /opt/protoc && \
    go env -w GOPROXY=https://goproxy.cn
#    echo export PATH="$PATH:$(go env GOPATH)/bin:/opt/protoc/bin" >> ~/.bashrc

# Install grpc
RUN go get -u google.golang.org/grpc \
    && go get -u github.com/golang/protobuf/protoc-gen-go \
    && go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
